config/routes.rb
RUBYGEM_NAME_MATCHER = /[A-Za-z0-9\-\_\.]+/
LAZY_RUBYGEM_NAME_MATCHER = /[A-Za-z0-9\-\_\.]+?/

Gemcutter::Application.routes.draw do

  ################################################################################
  # API v1

  namespace :api do
    namespace :v1 do
      resource :api_key, :only => :show do
        put :reset
      end

      resources :downloads, :only => :index

      constraints :id => RUBYGEM_NAME_MATCHER do
        resources :downloads, :only => :show

        resources :downloads, :only => :show

        resources :versions, :only => :show do
          resources :downloads, :only => :index, :controller => "versions/downloads" do
            collection do
              get :search
            end
          end
        end
      end

      resources :dependencies, :only => :index

      resources :rubygems, :path => "gems", :only => [:create, :show, :index], :id => LAZY_RUBYGEM_NAME_MATCHER, :format => /json|xml|yaml/ do
        collection do
          delete :yank
          put :unyank
        end
        constraints :rubygem_id => RUBYGEM_NAME_MATCHER do
          resource :owners, :only => [:show, :create, :destroy]
        end
      end

      resource :search, :only => :show

      resources :web_hooks, :only => [:create, :index] do
        collection do
          delete :remove
          post :fire
        end
      end
    end
  end

  ################################################################################
  # API v0

  scope :to => "api/deprecated#index" do
    get "api_key"
    put "api_key/reset"

    post "gems"
    get  "gems/:id.json"

    scope :path => "gems/:rubygem_id" do
      put  "migrate"
      post "migrate"
      get    "owners(.:format)"
      post   "owners(.:format)"
      delete "owners(.:format)"
    end
  end

  ################################################################################
  # UI

  resource  :search,    :only => :show
  resource  :dashboard, :only => :show
  resources :profiles,  :only => :show
  resource  :profile,   :only => [:edit, :update]
  resources :stats,     :only => :index

  resources :rubygems, :only => :index, :path => "gems" do
    constraints :rubygem_id => RUBYGEM_NAME_MATCHER do
      resource  :subscription, :only => [:create, :destroy]
      resources :versions,     :only => :index
      resource  :stats,        :only => :show
    end
  end

  constraints :id => RUBYGEM_NAME_MATCHER do
    resources :rubygems, :path => "gems", :only => [:show, :edit, :update] do

      constraints :rubygem_id => RUBYGEM_NAME_MATCHER do
        resources :versions, :only => :show do
          resource :stats, :only => :show
        end
      end
    end
  end

  ################################################################################
  # Clearance Overrides

  resource :session, :only => [:new, :create]
  scope :path => "users/:user_id" do
    resource :confirmation, :only => [:new, :create], :as => :user_confirmation
  end

  resources :passwords, :only => [:new, :create]

  resources :users do
    resource :password, :only => [:create, :edit, :update]
    resource :confirmation, :only => [:new, :create]
  end

  ################################################################################
  # Root

  root :to => "home#index"

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_filter :redirect_to_root, :unless => :signed_in?, :except => :show

  def edit
  end

  def show
    @user           = User.find_by_slug!(params[:id])
    @rubygems       = @user.rubygems_downloaded(10)
    @extra_rubygems = @user.rubygems_downloaded(nil, 10).to_a
  end

  def update
    if current_user.update_attributes(params[:user])
      if current_user.email_reset
        sign_out
        flash[:notice] = "You will receive an email within the next few minutes. " <<
                         "It contains instructions for reconfirming your account with your new email address."
        redirect_to root_path
      else
        flash[:notice] = "Your profile was updated."
        redirect_to edit_profile_path
      end
    else
      render :edit
    end
  end
end

app/views/profiles/_rubygem.html.erb
<li class="<%= "small" unless graph %>">
  <a href="<%= rubygem_path(rubygem) %>" class="profile-rubygem">
    <%= rubygem.name %>
    <em><%= rubygem.versions.most_recent %></em>
  </a>
  <a href="<%= rubygem_stats_path(rubygem) %>" class="profile-downloads">
    <div><%= t('download_count', :count => content_tag(:span, number_with_delimiter(rubygem.downloads))).html_safe %></div>
    <div><%= t('stats.show.daily_downloads', :count => content_tag(:span, number_with_delimiter(rubygem.downloads_today))).html_safe %></div>
  </a>
  <% if graph %>
    <div id="graph-<%= rubygem.id %>" class="profile-graph">
    </div>
  <% end %>
</li>

app/views/profiles/edit.html.erb
<% @title = t('.title') %>

<%= form_for current_user, :url => {:controller => 'profiles', :action => 'update'} do |form| %>
  <%= form.error_messages %>

  <div class="avatar_field">
    <%= form.label :avatar %>
    <%= gravatar(60) %>
    <%= link_to 'Change', 'http://www.gravatar.com' %>
  </div>

  <div class="text_field">
    <%= form.label :handle %>
    <%= form.text_field :handle, :size => 25 %>
  </div>

  <div class="text_field">
    <%= form.label :email %>
    <%= form.text_field :email, :size => 25 %>
  </div>

  <div class="submit_field">
    <%= form.submit "Update", :disable_with => t('form_disable_with') %>
  </div>

  <h3><%= t '.reset_password.title' %></h3>
  <p><%= t('.reset_password.text', :link => link_to(t('.reset_password.link_text'), new_password_url)).html_safe %></p>

  <h3><%= t '.api_access.title' %></h3>
  <p>
    <%= t('.api_access.key_is', :key => content_tag(:strong, current_user.api_key)).html_safe %><br />
    <%= t('.api_access.credentials', :gem_credentials_file => content_tag(:code, '~/.gem/credentials'),
                                     :gem_commands_link => link_to(t('.api_access.link_text'), page_url('gem_docs'))).html_safe %>
  </p>

<pre><code>---
:rubygems_api_key: <%= current_user.api_key %></code></pre>

<% end %>

<p><%= button_to t('.api_access.reset'), reset_api_v1_api_key_path, :method => :put, :confirm => t('.api_access.confirm_reset') %></p>

app/views/profiles/show.html.erb
<% content_for :title do %>
  <div id="avatar-frame">
    <%= gravatar(64, "profile_gravatar", @user) %>
  </div>
  <div id="profile-info">
    <h2 id="profile-name"><%= link_to @user.display_handle, profile_path(@user.display_id) %></h2>
    <h3 id="profile-email"><%= mail_to @user.email, "(email)", :encode => "hex" %></h3>
  </div>
  <div id="downloads-ego">
    <% if @user == current_user %>
      <%= link_to "Edit Profile", edit_profile_path, :id => "edit-profile" %>
    <% end %>
    <h5 id="downloads">Downloads</h5>
    <div id="downloads_count">
      <div><strong><%= number_with_delimiter(@user.today_downloads_count) %></strong> today</div>
      <div><strong><%= number_with_delimiter(@user.total_downloads_count) %></strong> all time</div>
    </div>
  </div>
<% end %>

<% content_for :javascript do %>
  <%= javascript_include_tag "raphael", "g.raphael", "g.bar" %>
  <script type="text/javascript">
    $(document).ready(function() {
      var dates = <%= Rubygem.monthly_short_dates.to_json.html_safe %>;
      <% @rubygems.each do |rubygem| %>
        $.data(document.body, "graph-<%= rubygem.id %>", <%= rubygem.monthly_downloads.to_json.html_safe %>);
      <% end %>

      $(".profile-graph").each(function() {
        var id   = $(this).attr("id"),
            r    = Raphael(id),
            fin  = function () {
              var currentDate = dates[Math.floor(this.bar.x / 22 - 1)]
              this.flag = r.g.popup(this.bar.x, this.bar.y, currentDate + ": " + this.bar.value || "0").insertBefore(this);
            },
            fout = function () {
              this.flag.animate({opacity: 0}, 300, function () {this.remove();});
            };

        r.g.barchart(15, 9, 655, 125,
          [ $.data(document.body, id) ],
          { type: "soft", colors : { 0 : "rgb(200, 164, 164)" } }
        ).hover(fin, fout);
      });
    });
  </script>
<% end %>

<div id="profile">
  <div class="profile-list">
    <ol>
      <%= render :partial => 'rubygem', :collection => @rubygems, :locals => {:graph => true}  %>
      <%= render :partial => 'rubygem', :collection => @extra_rubygems, :locals => {:graph => false} %>
    </ol>
  </div>
</div>