config/routes.rb
RUBYGEM_NAME_MATCHER = /[A-Za-z0-9\-\_\.]+/
LAZY_RUBYGEM_NAME_MATCHER = /[A-Za-z0-9\-\_\.]+?/

Gemcutter::Application.routes.draw do

  ################################################################################
  # API v1

  namespace :api do
    namespace :v1 do
      resource :api_key, :only => :show do
        put :reset
      end

      resources :downloads, :only => :index

      constraints :id => RUBYGEM_NAME_MATCHER do
        resources :downloads, :only => :show

        resources :downloads, :only => :show

        resources :versions, :only => :show do
          resources :downloads, :only => :index, :controller => "versions/downloads" do
            collection do
              get :search
            end
          end
        end
      end

      resources :dependencies, :only => :index

      resources :rubygems, :path => "gems", :only => [:create, :show, :index], :id => LAZY_RUBYGEM_NAME_MATCHER, :format => /json|xml|yaml/ do
        collection do
          delete :yank
          put :unyank
        end
        constraints :rubygem_id => RUBYGEM_NAME_MATCHER do
          resource :owners, :only => [:show, :create, :destroy]
        end
      end

      resource :search, :only => :show

      resources :web_hooks, :only => [:create, :index] do
        collection do
          delete :remove
          post :fire
        end
      end
    end
  end

  ################################################################################
  # API v0

  scope :to => "api/deprecated#index" do
    get "api_key"
    put "api_key/reset"

    post "gems"
    get  "gems/:id.json"

    scope :path => "gems/:rubygem_id" do
      put  "migrate"
      post "migrate"
      get    "owners(.:format)"
      post   "owners(.:format)"
      delete "owners(.:format)"
    end
  end

  ################################################################################
  # UI

  resource  :search,    :only => :show
  resource  :dashboard, :only => :show
  resources :profiles,  :only => :show
  resource  :profile,   :only => [:edit, :update]
  resources :stats,     :only => :index

  resources :rubygems, :only => :index, :path => "gems" do
    constraints :rubygem_id => RUBYGEM_NAME_MATCHER do
      resource  :subscription, :only => [:create, :destroy]
      resources :versions,     :only => :index
      resource  :stats,        :only => :show
    end
  end

  constraints :id => RUBYGEM_NAME_MATCHER do
    resources :rubygems, :path => "gems", :only => [:show, :edit, :update] do

      constraints :rubygem_id => RUBYGEM_NAME_MATCHER do
        resources :versions, :only => :show do
          resource :stats, :only => :show
        end
      end
    end
  end

  ################################################################################
  # Clearance Overrides

  resource :session, :only => [:new, :create]
  scope :path => "users/:user_id" do
    resource :confirmation, :only => [:new, :create], :as => :user_confirmation
  end

  resources :passwords, :only => [:new, :create]

  resources :users do
    resource :password, :only => [:create, :edit, :update]
    resource :confirmation, :only => [:new, :create]
  end

  ################################################################################
  # Root

  root :to => "home#index"

end

app/views/layouts/_feeds.html.erb
<% if signed_in? %>
  <%= atom_feed_link t(:feed_subscribed), dashboard_url(:api_key => current_user.api_key, :format => :atom) %>
<% end %>

<%= atom_feed_link t(:feed_latest), 'http://feeds.feedburner.com/gemcutter-latest' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
    <link rel="fluid-icon" href="/apple-touch-icon.png"/>
    <link rel="search" type="application/opensearchdescription+xml" title="<%=t :title %>" href="/opensearch.xml">
    <%= stylesheet_link_tag "reset", "960", "screen", :cache => true %>
    <!--[if IE 7]>
      <%= stylesheet_link_tag "ie7" %>
    <![endif]-->
    <%= render "layouts/feeds" %>
    <%= csrf_meta_tag %>
    <title><%= page_title %></title>
  </head>
  <body>
    <div class="container_12">
      <div class="prefix_1 grid_4 header">
        <h1><%= link_to t(:title), root_url, :title => "Home" %></h1>
      </div>
      <div class="grid_6 suffix_1 nav">
        <div id="nav-cap">
          <div id="nav">
            <% if signed_in? %>
                <div id="user-info">
                  <a href="<%= profile_path(current_user) %>">
                    <%= gravatar(32, "user_gravatar") %>
                    <span><%= truncate(current_user.name) %></span>
                  </a>
                </div>
                <ul id="signed_in">
                  <li id="all-gems"><%= link_to t('.header.all_gems'), rubygems_url %></li>
                  <li id="dashboard"><%= link_to t('.header.dashboard'), dashboard_url %></li>
                  <li id="sign-out"><%= link_to t('.header.sign_out'), sign_out_path, :method => :delete %></li>
                </ul>
            <% else %>
              <ul id="signed_out">
                <li id="all-gems"><%= link_to "all gems", rubygems_url %></li>

                <li id="sign-in">
                  <a href="<%= ssl_url_for :controller => 'clearance/sessions',
                                           :action     => 'new' %>"><%= t('.header.sign_in') %></a>
                </li>

                <li id="sign-up">
                  <a href="<%= ssl_url_for :controller => 'clearance/users',
                                           :action     => 'new' %>"><%= t('.header.sign_up') %></a>
                </li>
              </ul>
            <% end %>
          </div>
        </div>
        <%= form_tag search_url, :id => "main-search", :method => :get do %>
          <%= text_field_tag :query, params[:query] ? params[:query] : "Search gems&hellip;".html_safe %>
          <%= submit_tag 'Search', :id => 'search_submit', :name => nil %>
        <% end %>
      </div>
      <div class="prefix_1 grid_10 suffix_1 main">
        <% flash.each do |name, msg| %>
          <div id="flash-border">
            <div id="flash_<%= name %>"><span><%= msg %></span></div>
          </div>
        <% end %>
        <%= render :partial => "announcements/announcement_for_all" %>
        <% if content_for?(:fold) %>
          <div class="fold">
            <%= yield :fold %>
          </div>
        <% end %>
        <div class="info clearfix">
          <div class="title">
            <% if @title %>
              <h2><%= link_to @title, @title_url %></h2>
            <% end %>
            <% if @subtitle %>
              <h3><%= @subtitle.html_safe %></h3>
            <% end %>
            <%= yield :title %>
          </div>
          <%= yield %>
        </div>
      </div>
      <div class="prefix_1 grid_10 suffix_1 footer">
        <div class="links">
          <%= link_to t('.footer.about'), page_url("about") %>
          <%= link_to t('.footer.blog'), "http://update.gemcutter.org" %>
          <%= link_to t('.footer.guides'), "http://guides.rubygems.org"  %>
          <%= link_to t('.footer.help'), t(:help_url) %>
          <%= link_to t('.footer.status'), "http://twitter.com/gemcutter" %>
          <%= link_to t('.footer.source_code'), "http://github.com/rubygems/gemcutter" %>
          <%= link_to t('.footer.discussion_forum'), "http://groups.google.com/group/gemcutter" %>
          <%= link_to t('.footer.statistics'), stats_url %>
          <%= link_to t('.footer.designed_by', :designer => image_tag('thoughtbot.png')).html_safe, "http://thoughtbot.com",
            :class => "sponsor",
            :title => t('.footer.designed_by_title', :designer => 'Thoughtbot'),
            :id    => "thoughtbot" %>
          <%= link_to t('.footer.resolved_with', :resolver => image_tag('dnsimple.png')).html_safe, "http://dnsimple.com",
            :title => t('.footer.resolved_with_title', :resolver => 'DNSimple'),
            :class => "sponsor",
            :id    => "dnsimple" %>
          <%= link_to t('.footer.supported_by', :supporter => image_tag('rubycentral.png')).html_safe, "http://rubycentral.org",
            :title => t('.footer.supported_by_title', :supporter => 'Ruby Central'),
            :class => "sponsor",
            :id    => "rubycentral" %>
        </div>
      </div>
    </div>
    <%= javascript_include_tag "jquery", "jquery.easing.1.3", "jquery.color", "announcements", "application", "rails", :cache => true %>
    <%= yield :javascript %>
    <script type="text/javascript">
    var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
    document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
    </script>
    <script type="text/javascript">
    try {
    var pageTracker = _gat._getTracker("UA-10315684-1");
    pageTracker._trackPageview();
    } catch(err) {}</script>
  </body>
</html>